name: RaceCarAI
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - matplotlib=3.6.2
  - numpy=1.22.3
  - pygame=2.5.2
  - pytorch=2.1.0
  - pip
  - pip:
    - imgui
    - imgui[pygame]
